### ISSUE TITLE
有考虑支持玩家列表的彩色字符吗

### ISSUE THREAD

**Issue by fffzzl** [Under-estimate/McMotd#11]
有些插件能修改玩家列表塞入一些信息，游戏中也能正常转换彩色字符，有考虑支持一下吗。
测试ip mc.funmc.cc  
![SDP_O%K06D_MC@DZ@0LTG X](https://user-images.githubusercontent.com/67791411/205440620-199b61a8-d1ad-4641-a399-9c921a8f95bf.png)

**Comment by Under-estimate** [comment]
目前效果：
![9TCR$4TUYZRDVU)H4W8 UHB](https://user-images.githubusercontent.com/55307932/206635195-3b144bd5-fd10-41d6-836d-6a2699b1c1dc.png)
