### ISSUE TITLE
无法开启在线人数记录功能

### ISSUE THREAD

**Issue by LTHPKBTE** [Under-estimate/McMotd#12]
如题，无论是输入`/mcrec mc.hypixel.net enable`还是`/mcrec mc.hypixel.net disable`都返回"已停止记录mc.hypixel.net的在线人数"。后台没有报错。
十一月之前运行正常。

**Comment by LTHPKBTE** [comment]
虽然是我的问题 但是help里为什么提示是enable....

**Comment by LTHPKBTE** [comment]
行 明白了，我理解的问题，抱歉

**Comment by Under-estimate** [comment]
`/mcrec <address> <enable>`里的`<enable>`只是参数名，内容是要填`true`或`false`的。

`mirai-console`可能把`enable`和`disable`都解析为了`false`
