### ISSUE TITLE
Centos 7.6 无法调用中文字体

### ISSUE THREAD

**Issue by Simonchan93729** [Under-estimate/McMotd#14]
centos 7.6
已安装字体
![image](https://user-images.githubusercontent.com/19723613/210645323-e8e2f128-10a8-4b96-ad6e-3cbbc17da8c9.png)
选用字体
![image](https://user-images.githubusercontent.com/19723613/210645342-ce5e1378-3ef2-4a99-9f17-134bd290198f.png)
控制台字体报错
![image](https://user-images.githubusercontent.com/19723613/210645389-970985c1-f0f1-43a9-9e83-788dabd0515b.png)
输出结果
![image](https://user-images.githubusercontent.com/19723613/210645405-dd735825-2562-4b1f-b21c-92b0d2d1117a.png)

如何解决并正确调用中文字体

**Comment by Under-estimate** [comment]
检查一下字体文件是否有权限访问，使用`chmod 644 <字体文件>`命令更改字体文件权限。以下配置经测试可以正常使用：
![image](https://user-images.githubusercontent.com/55307932/210796298-aae26d45-31fd-4054-a296-df82f040afef.png)

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210936510-560101fa-0b10-420c-a99c-999ee65863bf.png)
![image](https://user-images.githubusercontent.com/19723613/210936533-99948e7f-742d-4132-b602-6ebdd3f5d1d7.png)
![image](https://user-images.githubusercontent.com/19723613/210936566-e6efa018-0c4f-4d12-8d0b-502f62b8258f.png)
依然不行
![image](https://user-images.githubusercontent.com/19723613/210936614-65ada0f9-3756-41ac-b4cf-0e09fe3fd6a1.png)

**Comment by Under-estimate** [comment]
可以尝试一下这个版本：[mcmotd-1.1.12-beta.zip](https://github.com/Under-estimate/McMotd/files/10357813/mcmotd-1.1.12-beta.zip)，下载解压后选择`mcmotd-1.1.12.mirai.jar`**或**`mcmotd-1.1.12.mirai2.jar`替换掉plugins文件夹中原来的插件，并在配置文件中使用`fontPath`手动指定字体路径（指定`fontPath`后，插件会忽略`fontName`配置项）：
![image](https://user-images.githubusercontent.com/55307932/210943270-e30f8378-b76b-4b73-89ed-00f9c927a47c.png)
如果顺利的话，应该可以看到如下的输出：
![image](https://user-images.githubusercontent.com/55307932/210943670-cdd2db77-8f9b-4a06-a9fb-dd1674f0c49f.png)

**Comment by Simonchan93729** [comment]
可以在新版本上添加font path吗

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210947151-33874af1-3abe-4c7f-bca4-784242747501.png)

**Comment by Simonchan93729** [comment]
还是读取不了

**Comment by Under-estimate** [comment]
> ![image](https://user-images.githubusercontent.com/19723613/210947151-33874af1-3abe-4c7f-bca4-784242747501.png)

这个报错是因为字体文件不存在，你可以在这个终端里面检查一下路径有没有写错（`ls /usr/share/fonts/chinese/TrueType/STCAIYUN.TTF`）如果路径确实没写错的话，也许可以把字体文件复制到其他位置试试？比如放到和mirai相同的文件夹下再尝试指定路径？
![image](https://user-images.githubusercontent.com/55307932/210949071-7984526b-ee94-4cf8-96ac-a098da18c6fd.png)

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210949486-499a6593-3594-464a-9e64-2bafee310dd8.png)
终端是可以读取的

**Comment by Simonchan93729** [comment]
现在可以读取了 
可能是因为我用的mcmanager的原因无法读取系统
但是出图还是乱码

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210950668-ce1fde85-a1f7-44a5-bcbf-b8e8aa0445cb.png)

![image](https://user-images.githubusercontent.com/19723613/210950756-0b11339a-0daa-4954-810b-a22e8cb2bd21.png)

**Comment by Under-estimate** [comment]
[新发布的Release](https://github.com/Under-estimate/McMotd/releases)应该解决了这个问题，你可以试一下

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210955817-1308de3f-8e73-49ae-9ac3-7cc60df030e1.png)
看到可以读取字体了
但是输出图片还是乱码
![image](https://user-images.githubusercontent.com/19723613/210955926-b06404be-cbd9-4633-8349-0b8f743f5e91.png)

**Comment by Under-estimate** [comment]
在启动mcl的脚本里加一个`-Dfile.encoding=utf-8`试试？
![image](https://user-images.githubusercontent.com/55307932/210963412-b755ced8-ca2c-4e08-88c0-6c8f3eb34356.png)

**Comment by Simonchan93729** [comment]
![image](https://user-images.githubusercontent.com/19723613/210966312-0fe6864f-01f6-469e-9bd4-d12faa9392d6.png)

**Comment by Simonchan93729** [comment]
这是我mcl的启动参数

**Comment by Under-estimate** [comment]
你用的是这个[mcsmanager](https://mcsmanager.com/)吗，我装一下试试

**Comment by Simonchan93729** [comment]
> 你用的是这个[mcsmanager](https://mcsmanager.com/)吗，我装一下试试

对

**Comment by Simonchan93729** [comment]
用的opensdk17
![image](https://user-images.githubusercontent.com/19723613/210976783-733459fd-44cd-42fe-af98-ba7fd5320de1.png)
![image](https://user-images.githubusercontent.com/19723613/210976885-2ca922d5-69a4-466c-b29b-bb280746a64d.png)
----
![image](https://user-images.githubusercontent.com/19723613/210977004-53d85893-46d6-42fe-993f-a98549840ee0.png)
`java -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -jar mcl.jar 
`
![image](https://user-images.githubusercontent.com/19723613/210977130-7925fb2e-3571-42bb-9a52-246da149c550.png)

**Comment by Simonchan93729** [comment]
然后我centos的系统语言是这个
![1(XS(G73 C`@E7`717{{ L](https://user-images.githubusercontent.com/19723613/210988044-8e3be7d2-9aaa-4951-8687-6fc40c3d7a6a.png)

**Comment by Under-estimate** [comment]
刚刚复现了你的问题，解决方案是把中间标红的这一段删掉，只保留`-Dfile.encoding=UTF-8`
![image](https://user-images.githubusercontent.com/55307932/211009662-b70525e0-1f96-4061-bf18-17ad8a28f9e8.png)

**Comment by Simonchan93729** [comment]
> 刚刚复现了你的问题，解决方案是把中间标红的这一段删掉，只保留`-Dfile.encoding=UTF-8` ![image](https://user-images.githubusercontent.com/55307932/211009662-b70525e0-1f96-4061-bf18-17ad8a28f9e8.png)


可以正常显示中文了
