### ISSUE TITLE
未来更新版本是否会有api

### ISSUE THREAD

**Issue by Simonchan93729** [Under-estimate/McMotd#15]
具体的Api是可以直接通过网站
如官网、博客等等
直接调用链接获取
最新服务器的MCmotd图片
并在每次刷新网站时更新图片

**Comment by Under-estimate** [comment]
这个功能可以有

**Comment by Simonchan93729** [comment]
建议采用监听端口的方式【如TCP PORT：9999】
以及配置文件默认服务器ip跟端口【如：1：www.baidu.com:25565|2：www.baidu.com:25566】
网站通过如www.baidu.com:9999/?server=1
这样可以获取1的服务器MCmotd图片
网站通过如www.baidu.com:9999/?server=2
这样可以获取2的服务器MCmotd图片

这样也有安全性不会被人随意调用接口
来获取自己服务器的MCmotd图片
