### ISSUE TITLE
请问如何添加背景图片

### ISSUE THREAD

**Issue by AsColdnet** [Under-estimate/McMotd#19]
![QQ图片20231215020859](https://github.com/Under-estimate/McMotd/assets/136914640/8459f78a-c618-4dbe-95e8-5099acfa5c66)
<img width="209" alt="Snipaste_2023-12-15_02-40-51" src="https://github.com/Under-estimate/McMotd/assets/136914640/f8cb4d37-1967-461f-bc92-0545d308cfb5">
这样设置后还是不行

**Comment by Under-estimate** [comment]
请检查一下控制台日志里是否有类似内容：
```text
2023-12-15 14:47:30 W/Minecraft MOTD Fetcher: 无法打开指定的背景图片: ./background.png
```
如果有的话，说明配置文件中的路径不正确或背景图片文件不存在。
你在配置背景图片时使用的是**相对路径**，请确认**当前工作目录**下存在`background.png`文件。
如果你不清楚mcsmanager的当前工作目录是什么，可以改用背景图片文件的绝对路径。

**Comment by AsColdnet** [comment]
你好，运行地址是插件目录下吗

**Comment by Under-estimate** [comment]
运行地址（当前工作目录）是执行**启动命令**时所在的文件夹。
例如，
在`/home/foo`下运行`./mcl`启动Mirai时，当前工作目录为`/home/foo`
在`/home`下运行`./foo/mcl`启动Mirai时，当前工作目录为`/home`

**Comment by AsColdnet** [comment]
非常感谢，已经解决了🤗
