### ISSUE TITLE
[功能请求]query玩家列表和ping服务器使用不同端口

### ISSUE THREAD

**Issue by XC084** [Under-estimate/McMotd#23]
[今天早上的图像问题是因为icon过于高清](https://mirai.mamoe.net/post/27941)☝🏻👿
![Image_1716119938893](https://github.com/Under-estimate/McMotd/assets/99209606/3b0d8eac-72c5-4b4a-b8b4-b2ba4115a8a8)
已解决。

提到的另一个玩家列表获取失败的问题，是因为服务器限制较多。
玩家列表在：
> a.mc.shanwer.top:31032
而服务器的端口号在：
> a.mc.shanwer.top:22684

解决问题中ing：
![Image_1716120268135](https://github.com/Under-estimate/McMotd/assets/99209606/3d5f86ce-7da4-4a16-8e80-1c64400f0f88)
问题描述：
![Image_1716120144267](https://github.com/Under-estimate/McMotd/assets/99209606/2322d50f-464f-45b6-8bf0-302b5c60c305)
放弃挣扎：
![Image_1716120120539](https://github.com/Under-estimate/McMotd/assets/99209606/06bd49c3-7b06-4879-ab97-1e32da2d9c81)

如果可以的话加入[QQ群](https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=0JGheiu9D-MsJVd15QVkwNSIzO8tfBX8&authKey=csmBoCTmstSjetqQUahlivgBsjXGqZVDmUiXzguXFq8cMPs0eMaO3dNIRKHbxIe5&noverify=0&group_code=593263022)进行更及时的沟通，在线修bug×，拷打笨蛋用户√

**Comment by XC084** [comment]
> [今天早上的图像问题是因为icon过于高清](https://mirai.mamoe.net/post/27941)☝🏻👿 ![Image_1716119938893](https://private-user-images.githubusercontent.com/99209606/331870316-3b0d8eac-72c5-4b4a-b8b4-b2ba4115a8a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjE2NjEsIm5iZiI6MTcxNjEyMTM2MSwicGF0aCI6Ii85OTIwOTYwNi8zMzE4NzAzMTYtM2IwZDhlYWMtNzJjNS00YjRhLWI4YjQtYjJiYTQxMTVhOGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMzRkZGVlOTY4MTgwMDlmMTIwNWMzMzIxOWZhMTZlYzAxODVlNjI3NjE2MGExNDViZDU1YjhlNDdiMjJlMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHYSVJpV6NW39ry3dD7iyoRAdrSA7e8CZNAjukC4Ks0) 已解决。
> 
> 提到的另一个玩家列表获取失败的问题，是因为服务器限制较多。 玩家列表在：
> 
> > a.mc.shanwer.top:31032
而服务器的端口号在：
> > a.mc.shanwer.top:22684
> 
> 解决问题中ing： ![Image_1716120268135](https://private-user-images.githubusercontent.com/99209606/331870572-3d5f86ce-7da4-4a16-8e80-1c64400f0f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjE2NjEsIm5iZiI6MTcxNjEyMTM2MSwicGF0aCI6Ii85OTIwOTYwNi8zMzE4NzA1NzItM2Q1Zjg2Y2UtN2RhNC00YTE2LThlODAtMWM2NDQwMGYwZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYjNjODhhYmFmNTJjMDBhYzA0MzlhN2RjOGVlMjQ4NDA2MmM2MzNiOTZhMzk5MDBhYWM0YjA3YWRmNmI4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xuxCEwi7L7jJcaROu31HNaJTw6T0z6JRqac_33fdXCE) 问题描述： ![Image_1716120144267](https://private-user-images.githubusercontent.com/99209606/331870597-2322d50f-464f-45b6-8bf0-302b5c60c305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjE2NjEsIm5iZiI6MTcxNjEyMTM2MSwicGF0aCI6Ii85OTIwOTYwNi8zMzE4NzA1OTctMjMyMmQ1MGYtNDY0Zi00NWI2LThiZjAtMzAyYjVjNjBjMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMmMxMWJjYmMxMDA0YjQ1N2RjYWY1ZjViZTcwYjFiZTlmMzQwMTlmMjZkZWRmNzU3ZWEyMDVmOGJiMWZmZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1vAoBmPrK3HI5adkYeAyt5VZY8xoqVfdQ9jzbi-b2w) 放弃挣扎： ![Image_1716120120539](https://private-user-images.githubusercontent.com/99209606/331870600-06bd49c3-7b06-4879-ab97-1e32da2d9c81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjE2NjEsIm5iZiI6MTcxNjEyMTM2MSwicGF0aCI6Ii85OTIwOTYwNi8zMzE4NzA2MDAtMDZiZDQ5YzMtN2IwNi00ODc5LWFiOTctMWUzMmRhMmQ5YzgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMjI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5M2U0NzJjMTcwYWEzZmUxYWMxYTM4ZDNhMjc0M2VkYjcwMzIwZGQwOWYwOGI0NmVhZjlhMzRlMmRhZWZmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SREB7rzeNfaM6jO2IITQ08nx135mxHaWDp-XmRLM_oU)
> 
> 如果可以的话加入[QQ群](https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=0JGheiu9D-MsJVd15QVkwNSIzO8tfBX8&authKey=csmBoCTmstSjetqQUahlivgBsjXGqZVDmUiXzguXFq8cMPs0eMaO3dNIRKHbxIe5&noverify=0&group_code=593263022)进行更及时的沟通，在线修bug×，拷打笨蛋用户√

**Comment by XC084** [comment]
点错了😅（

**Comment by Under-estimate** [comment]
插件的玩家列表获取功能目前用的是[Server List Ping](https://wiki.vg/Server_List_Ping)协议，[Query](https://wiki.vg/Query)协议还不支持

**Comment by Under-estimate** [comment]
目前添加了对Query协议的支持，需要进一步测试（我本地搭建的原版服务器可以成功请求到query信息，但是你的服务器似乎没有响应31032端口上的query请求）  
  
若要启用Query功能，请在原有服务器地址后指定Query端口。例如使用`/mcp a.mc.shanwer.top:22684:31032`来从22684端口获取motd和服务器icon（使用ServerListPing协议），并从31032端口获取玩家列表（使用Query协议）  
  
附件：[mcmotd-query-test.zip](https://github.com/user-attachments/files/15572925/mcmotd-query-test.zip)

**Comment by zzj2039** [comment]
> 目前添加了对Query协议的支持，需要进一步测试（我本地搭建的原版服务器可以成功请求到query信息，但是你的服务器似乎没有响应31032端口上的query请求）
> 
> 若要启用Query功能，请在原有服务器地址后指定Query端口。例如使用`/mcp a.mc.shanwer.top:22684:31032`来从22684端口获取motd和服务器icon（使用ServerListPing协议），并从31032端口获取玩家列表（使用Query协议）
> 
> 附件：[mcmotd-query-test.zip](https://github.com/user-attachments/files/15572925/mcmotd-query-test.zip)

似乎用不了，有没有单独查询query的指令，我测试不出来

**Comment by Under-estimate** [comment]
目前Query查询只用于在ServerListPing不提供玩家列表的情况下，补全玩家列表信息。执行mcp命令时如果带上了query端口，后台不报错应该就是查询成功了。

**Comment by XC084** [comment]
> 目前添加了对Query协议的支持，需要进一步测试（我本地搭建的原版服务器可以成功请求到query信息，但是你的服务器似乎没有响应31032端口上的query请求）
> 
> 若要启用Query功能，请在原有服务器地址后指定Query端口。例如使用来从22684端口获取motd和服务器图标（使用ServerListPing协议），并从31032端口获取玩家列表（使用Query协议）`/mcp a.mc.shanwer.top:22684:31032`
> 
> 附件：[mcmotd-query-test.zip](https://github.com/user-attachments/files/15572925/mcmotd-query-test.zip)

成功了
(我们服务器的端口之前努力改到一个上面了,因为这样更方便查)https://api.mcstatus.io/v2/status/java/a.mc.shanwer.top:22684
/mcp a.mc.shanwer.top:22684:22684
![e788203ce5ac13ae0ac41ff012e9c655_0](https://github.com/Under-estimate/McMotd/assets/99209606/8d2b8b1f-8cb1-4af1-98ab-c257e47f6ab6)
感谢
