### ISSUE TITLE
功能请求: 显示历史最高人数

### ISSUE THREAD

**Issue by zzj2039** [Under-estimate/McMotd#26]
为开启了人数记录的服务器一并记录历史最高在线人数并显示

**Comment by Under-estimate** [comment]
如果要显示历史最高在线人数的话，显示在哪里会比较合适？

**Comment by zzj2039** [comment]
或许可以尝试把在线人数改成：在线人数/历史最高在线人数

**Comment by Under-estimate** [comment]
> 或许可以尝试把在线人数改成：在线人数/历史最高在线人数

这个不太好吧，目前显示的是 在线人数/服务器人数上限

**Comment by zzj2039** [comment]
> > 或许可以尝试把在线人数改成：在线人数/历史最高在线人数
> 
> 这个不太好吧，目前显示的是 在线人数/服务器人数上限

事实上很多服务器的人数上限都是假的

**Comment by zzj2039** [comment]
> > 或许可以尝试把在线人数改成：在线人数/历史最高在线人数
> 
> 这个不太好吧，目前显示的是 在线人数/服务器人数上限

可以加个开关让用户选择要不要这样显示
