### ISSUE TITLE
当版本列表过长时，玩家组件等不渲染

### ISSUE THREAD

**Issue by Longtianmu** [Under-estimate/McMotd#4]
![`TIYWMV7IH~HUS~NKQAB 9S](https://user-images.githubusercontent.com/60567448/169193054-65edc308-47bb-4f49-ab0f-873e6dbef57b.png)
如图所示，是否可以将版本写成范围，或直接在超出长度时省略?

**Comment by Under-estimate** [comment]
该问题已修复，请查看[最新版本](https://github.com/Under-estimate/McMotd/releases)。
