### ISSUE TITLE
部分地址查询时回复速度较慢

### ISSUE THREAD

**Issue by itzdrli** [Under-estimate/McMotd#7]
如题，不确定是机器人被腾讯风控（？）的问题还是被查询主机/机器人主机问题，
返回的图片内延迟基本都在40/50ms以下；
机器人主机50M BGP+1c2g；
被查询主机未知。

还需要啥信息直接说
或者QQ联系：3327930436

**Comment by Under-estimate** [comment]
1. 实际查询需要发送两个请求，查询结果图片中显示的是第二个ping请求的延迟，首个请求的延迟可能会高一些
2. 查询结果图片上传到群聊也需要时间

**Comment by itzdrli** [comment]
> 1. 实际查询需要发送两个请求，查询结果图片中显示的是第二个ping请求的延迟，首个请求的延迟可能会高一些
> 
>     2. 查询结果图片上传到群聊也需要时间

1. 这些我都知道，但是很多地址在非首次查询的时候也会出现需要等待几十秒甚至1-2分钟后才会回复；
2. 有可能我主机网络有问题（？这得问电信）
