### ISSUE TITLE
在指定群聊禁用

### ISSUE THREAD

**Issue by Seayay** [Under-estimate/McMotd#9]

**Comment by Under-estimate** [comment]
本插件使用了标准的mirai命令接口，因此可以通过配置群聊的权限来实现此功能。
[mirai-console权限文档](https://github.com/mamoe/mirai-console/blob/master/docs/Permissions.md)

检查指定群聊是否有使用此插件的权限：`perm pp m<群号>.* org.zrnq.mcmotd:*`
检查指定群员是否有使用此插件的权限：`perm pp m<群号>.<群员qq号> org.zrnq.mcmotd:*`或`perm pp u<群员qq号> org.zrnq.mcmotd:*`
撤销对指定群聊的授权：`perm deny m<群号>.* org.zrnq.mcmotd:*`
撤销对指定群员的授权：`perm deny m<群号>.<群员qq号> org.zrnq.mcmotd:*`或`perm deny u<群员qq号> org.zrnq.mcmotd:*`
